Algoritmo "MENU_PQ_EU_GOSTO"

Var
// Seção de Declarações das variáveis 
   opcao: caractere
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   opcao <- "s"
   enquanto ( opcao = "s") faca
      escreval("Palmeiras não tem mundial")
      escreval("=========================")
      escreva("Receber essa verdade mais uma vez (s/n): ")
      leia(opcao)
   fimenquanto

Fimalgoritmo